[package]
name = "apricorn-desktop"
description = "Desktop app shell (Windows / Linux / macOS)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "apricorn"
path = "src/main.rs"

[dependencies]
apricorn-core.workspace = true
apricorn-gfx.workspace = true
pollster = "1.0.1"
wgpu = "30.0.1"
winit = "0.30"

[lints]
workspace = true